name: atomvision-action

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy scipy matplotlib==3.6.0
        python setup.py install

    - name: Lint
      run: |
        pip install flake8 pytest pycodestyle pydocstyle
        pycodestyle --ignore E203,W503 --exclude=tests atomvision
        pydocstyle --match-dir=core --match-dir=io --match-dir=io --match-dir=ai --match-dir=analysis --match-dir=db --match-dir=tasks --count atomvision
        flake8 --ignore E203,W503 --exclude=tests --statistics --count --exit-zero atomvision
    - name: Test with pytest
      run: |
        pip install flake8 pytest pycodestyle pydocstyle codecov pytest-cov coverage 
        echo 'PIP freeze'
        pip freeze
        coverage run -m pytest
        coverage report -m
        codecov
        #codecov --token="85bd9c5d-9e55-4f6d-bd69-350ee5e3bb41"

